AWSTemplateFormatVersion: 2010-09-09
Description: This Template sets up an AWS Inspector service for the datalake solution.
Parameters:
  EC2InstanceCreationStack:
    Description: The EC2 Template Name that contains EC2 Tags value
    Type: String
Mappings:
  RegionMap:
    us-east-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:us-east-1:316112463485:rulespackage/0-gEjTy7T7'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:us-east-1:316112463485:rulespackage/0-rExsr2X8'
      NetworkReachability: 'arn:aws:inspector:us-east-1:316112463485:rulespackage/0-PmNV0Tcd'
      SecurityBestPractices: 'arn:aws:inspector:us-east-1:316112463485:rulespackage/0-R01qwB5Q'
    us-east-2:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:us-east-2:646659390643:rulespackage/0-JnA8Zp85'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:us-east-2:646659390643:rulespackage/0-m8r61nnh'
      NetworkReachability: 'arn:aws:inspector:us-east-2:646659390643:rulespackage/0-cE4kTR30'
      SecurityBestPractices: 'arn:aws:inspector:us-east-2:646659390643:rulespackage/0-AxKmMHPX'
    us-west-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:us-west-1:166987590008:rulespackage/0-TKgzoVOa'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:us-west-1:166987590008:rulespackage/0-xUY8iRqX'
      NetworkReachability: 'arn:aws:inspector:us-west-1:166987590008:rulespackage/0-TxmXimXF'
      SecurityBestPractices: 'arn:aws:inspector:us-west-1:166987590008:rulespackage/0-byoQRFYm'
    us-west-2:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:us-west-2:758058086616:rulespackage/0-9hgA516p'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:us-west-2:758058086616:rulespackage/0-H5hpSawc'
      NetworkReachability: 'arn:aws:inspector:us-west-2:758058086616:rulespackage/0-rD1z6dpl'
      SecurityBestPractices: 'arn:aws:inspector:us-west-2:758058086616:rulespackage/0-JJOtZiqQ'
    ap-south-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:ap-south-1:162588757376:rulespackage/0-LqnJE9dO'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:ap-south-1:162588757376:rulespackage/0-PSUlX14m'
      NetworkReachability: 'arn:aws:inspector:ap-south-1:162588757376:rulespackage/0-YxKfjFu1'
      SecurityBestPractices: 'arn:aws:inspector:ap-south-1:162588757376:rulespackage/0-fs0IZZBj'
    ap-northeast-2:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:ap-northeast-2:526946625049:rulespackage/0-PoGHMznc'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:ap-northeast-2:526946625049:rulespackage/0-T9srhg1z'
      NetworkReachability: 'arn:aws:inspector:ap-northeast-2:526946625049:rulespackage/0-s3OmLzhL'
      SecurityBestPractices: 'arn:aws:inspector:ap-northeast-2:526946625049:rulespackage/0-2WRpmi4n'
    ap-southeast-2:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:ap-southeast-2:454640832652:rulespackage/0-D5TGAxiR'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:ap-southeast-2:454640832652:rulespackage/0-Vkd2Vxjq'
      NetworkReachability: 'arn:aws:inspector:ap-southeast-2:454640832652:rulespackage/0-FLcuV4Gz'
      SecurityBestPractices: 'arn:aws:inspector:ap-southeast-2:454640832652:rulespackage/0-asL6HRgN'
    ap-northeast-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-gHP9oWNT'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-7WNjqgGu'
      NetworkReachability: 'arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-YI95DVd7'
      SecurityBestPractices: 'arn:aws:inspector:ap-northeast-1:406045910587:rulespackage/0-bBUQnxMq'
    eu-central-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:eu-central-1:537503971621:rulespackage/0-wNqHa8M9'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:eu-central-1:537503971621:rulespackage/0-nZrAVuv8'
      NetworkReachability: 'arn:aws:inspector:eu-central-1:537503971621:rulespackage/0-6yunpJ91'
      SecurityBestPractices: 'arn:aws:inspector:eu-central-1:537503971621:rulespackage/0-ZujVHEPB'
    eu-west-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-ubA5XvBh'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-sJBhCr0F'
      NetworkReachability: 'arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-SPzU33xe'
      SecurityBestPractices: 'arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-SnojL3Z6'
    eu-west-2:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:eu-west-2:146838936955:rulespackage/0-kZGCqcE1'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:eu-west-2:146838936955:rulespackage/0-IeCjwf1W'
      NetworkReachability: 'arn:aws:inspector:eu-west-2:146838936955:rulespackage/0-AizSYyNq'
      SecurityBestPractices: 'arn:aws:inspector:eu-west-2:146838936955:rulespackage/0-XApUiSaP'
    eu-north-1:
      CommonVulnerabilitiesandExposures: 'arn:aws:inspector:eu-north-1:453420244670:rulespackage/0-IgdgIewd'
      CISOperatingSystemSecurityConfigurationBenchmarks: 'arn:aws:inspector:eu-north-1:453420244670:rulespackage/0-Yn8jlX7f'
      NetworkReachability: 'arn:aws:inspector:eu-north-1:453420244670:rulespackage/0-52Sn74uu'
      SecurityBestPractices: 'arn:aws:inspector:eu-north-1:453420244670:rulespackage/0-HfBQSbSf'
    us-gov-east-1:
      CommonVulnerabilitiesandExposures: >-
        arn:aws-us-gov:inspector:us-gov-east-1:206278770380:rulespackage/0-3IFKFuOb
      CISOperatingSystemSecurityConfigurationBenchmarks: >-
        arn:aws-us-gov:inspector:us-gov-east-1:206278770380:rulespackage/0-pTLCdIww
      SecurityBestPractices: >-
        arn:aws-us-gov:inspector:us-gov-east-1:206278770380:rulespackage/0-vlgEGcVD
    us-gov-west-1:
      CommonVulnerabilitiesandExposures: >-
        arn:aws-us-gov:inspector:us-gov-west-1:850862329162:rulespackage/0-4oQgcI4G
      CISOperatingSystemSecurityConfigurationBenchmarks: >-
        arn:aws-us-gov:inspector:us-gov-west-1:850862329162:rulespackage/0-Ac4CFOuc
      SecurityBestPractices: >-
        arn:aws-us-gov:inspector:us-gov-west-1:850862329162:rulespackage/0-rOTGqe5G
Resources:
  DWEventRuleIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AWS_Allow_Inspector_Assessment
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'inspector:StartAssessmentRun'
                Resource: '*'
      Description: Role for scheduled Inspector assessment from Cloudwatch Events
      Path: /
      Tags:
        - Key: Tag1
          Value: DWEventRuleIAMRole
  DatalakeEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: This event rule is used to schedule Inspector template
      ScheduleExpression: rate(7 days)
      State: ENABLED
      Targets:
        - Arn: !Ref DatalakeAssessmentTemplate
          Id: InspectorAssessmentTemplateTarget
          RoleArn: !GetAtt 
            - DWEventRuleIAMRole
            - Arn
  DatalakeEC2ResourceGroup:
    Type: 'AWS::Inspector::ResourceGroup'
    Properties:
      ResourceGroupTags:
        - Key: Name
          Value: !ImportValue 
            'Fn::Sub': '${EC2InstanceCreationStack}-TagValuePublicInstance'
        - Key: Name
          Value: !ImportValue 
            'Fn::Sub': '${EC2InstanceCreationStack}-TagValuePrivateInstance'
  DatalakeAssessmentTarget:
    Type: 'AWS::Inspector::AssessmentTarget'
    Properties:
      ResourceGroupArn: !Ref DatalakeEC2ResourceGroup
  DatalakeAssessmentTemplate:
    Type: 'AWS::Inspector::AssessmentTemplate'
    Properties:
      AssessmentTargetArn: !Ref DatalakeAssessmentTarget
      DurationInSeconds: 3600
      RulesPackageArns:
        - !FindInMap 
          - RegionMap
          - !Ref 'AWS::Region'
          - CommonVulnerabilitiesandExposures
        - !FindInMap 
          - RegionMap
          - !Ref 'AWS::Region'
          - CISOperatingSystemSecurityConfigurationBenchmarks
        - !FindInMap 
          - RegionMap
          - !Ref 'AWS::Region'
          - NetworkReachability
        - !FindInMap 
          - RegionMap
          - !Ref 'AWS::Region'
          - SecurityBestPractices
Outputs:
  DatalakeEC2ResourceGroup:
    Description: >-
      This output will get the EC2 resorce group ARN that is to be used as
      Assessment Target
    Value: !Ref DatalakeEC2ResourceGroup
    Export:
      Name: !Sub '${AWS::StackName}-DatalakeEC2ResourceGroup'
  DatalakeAssessmentTarget:
    Description: This is assessment target
    Value: !Ref DatalakeAssessmentTarget
    Export:
      Name: !Sub '${AWS::StackName}-DatalakeAssessmentTarget'
  DatalakeAssessmentTemplate:
    Description: This is Assessment template.
    Value: !Ref DatalakeAssessmentTemplate
    Export:
      Name: !Sub '${AWS::StackName}-DatalakeAssessmentTemplate'
  DWEventRuleIAMRole:
    Description: This is event rule target IAM role.
    Value: !Ref DWEventRuleIAMRole
    Export:
      Name: !Sub '${AWS::StackName}-DWEventRuleIAMRole'
  DWEventRuleIAMRoleArn:
    Description: This is event rule target IAM role arn.
    Value: !GetAtt 
      - DWEventRuleIAMRole
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-DWEventRuleIAMRoleArn'
  DatalakeEventRule:
    Description: This is Assessment template evevnt rule.
    Value: !Ref DatalakeEventRule
    Export:
      Name: !Sub '${AWS::StackName}-DatalakeEventRule'