AWSTemplateFormatVersion: '2010-09-09'
Description: Creating S3 Bucket for Datalake solution

Resources: 
  DatalakeS3bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256