Description: AWS Glue customized IAM Role and IAM Managed Policy Creation
Resources:
  DWGlueIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: >-
        This IAM role is associated with Glue Crawler and Glue Job to export
        DynamoDB tables to S3 bucket
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Path: /service-role/
      Tags:
        - Key: Tag1
          Value: DWGlueIAMRole
  DWGlueIAMRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: >-
        This IAM policy provides access to Glue to crawl and perform job
        activities. This is a customized policy and must be used for specific
        use cases
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
              - 'logs:*'
              - 'kms:*'
            Resource: '*'
      Roles:
        - !Ref DWGlueIAMRole
Outputs:
  DWGlueIAMRolePolicy:
    Description: >-
      This output holds the Data warehouse IAM managed policy with is associated
      with Glue IAM role that is created in this stack
    Value: !Ref DWGlueIAMRolePolicy
    Export:
      Name: !Sub '${AWS::StackName}-DWGlueIAMRolePolicy'
  DWGlueIAMRole:
    Description: >-
      This output holds the Data warehouse Glue IAM role which is associated
      with Glue crawler and job that are created in this stack
    Value: !Ref DWGlueIAMRole
    Export:
      Name: !Sub '${AWS::StackName}-DWGlueIAMRole'
  DWGlueIAMRoleArn:
    Description: >-
      This output holds the Data warehouse Glue IAM role which is associated
      with Glue crawler and job that are created in this stack
    Value: !GetAtt 
      - DWGlueIAMRole
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-DWGlueIAMRoleArn'