AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Sample Template for CloudWatch Logs.
Parameters:
  KMSStackName:
    Description: KMS Stack name through which desired KMS Key is created
    Type: String
  SNSTopicStackName:
    Description: >-
      Provide SNS Topic stack name through which SNS Topic will be associated
      with Alarms
    Type: String
Resources:
  WebServerLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: WebServerLogGroup
      RetentionInDays: 7
  404MetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: !Ref WebServerLogGroup
      FilterPattern: >-
        [ip, identity, user_id, timestamp, request, status_code = 404, size,
        ...]
      MetricTransformations:
        - MetricValue: '1'
          MetricNamespace: test/404s
          MetricName: test404Count
  BytesTransferredMetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: !Ref WebServerLogGroup
      FilterPattern: '[ip, identity, user_id, timestamp, request, status_code, size, ...]'
      MetricTransformations:
        - MetricValue: $size
          MetricNamespace: test/BytesTransferred
          MetricName: testBytesTransferred
  404Alarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: The number of 404s is greater than 2 over 2 minutes
      MetricName: test404Count
      Namespace: test/404s
      Statistic: Sum
      Period: '60'
      EvaluationPeriods: '2'
      Threshold: '2'
      AlarmActions:
        - !ImportValue
          'Fn::Sub': '${SNSTopicStackName}-TopicName'
      ComparisonOperator: GreaterThanThreshold
  BandwidthAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: The average volume of traffic is greater 3500 KB over 10 minutes
      MetricName: testBytesTransferred
      Namespace: test/BytesTransferred
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '2'
      Threshold: '3500'
      AlarmActions:
        - !ImportValue
          'Fn::Sub': '${SNSTopicStackName}-TopicName'
      ComparisonOperator: GreaterThanThreshold
Outputs:
  CloudWatchLogGroupName:
    Description: The name of the CloudWatch log group
    Value: !Ref WebServerLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-CloudWatchLogGroupName'
  CloudWatchLogGroupArn:
    Description: The name of the CloudWatch log group Arn
    Value: !GetAtt
      - WebServerLogGroup
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudWatchLogGroupArn'
