--- 
AWSTemplateFormatVersion: '2010-09-09'
Description: Creating KMS CMK for Datalake solution.

DatalakeKey: 
  Properties: 
    Description: "Datalake symmetric CMK"
    KeyPolicy: 
      Id: key-default-1
      Statement: 
        - 
          Action: "kms:*"
          Effect: Allow
          Principal: 
            AWS: "arn:aws:iam::xxxxxxxxxx:root"
            Resources: "*"
          Sid: "Enable IAM User Permissions"
        - 
          Action: 
            - "kms:Create*"
            - "kms:Describe*"
            - "kms:Enable*"
            - "kms:List*"
            - "kms:Put*"
            - "kms:Update*"
            - "kms:Revoke*"
            - "kms:Disable*"
            - "kms:Get*"
            - "kms:Delete*"
            - "kms:ScheduleKeyDeletion"
            - "kms:CancelKeyDeletion"
          Effect: Allow
          Principal: 
            AWS: "arn:aws:iam::xxxxxxxxxxx:user/jchirayathADMIN"
            Resources: "*"
          Sid: "Allow administration of the key"
        - 
          Action: 
            - "kms:DescribeKey"
            - "kms:Encrypt"
            - "kms:Decrypt"
            - "kms:ReEncrypt*"
            - "kms:GenerateDataKey"
            - "kms:GenerateDataKeyWithoutPlaintext"
          Effect: Allow
          Principal: 
            AWS: "arn:aws:iam::xxxxxxxxx:user/kmsuser"
            Resources: "*"
          Sid: "Allow use of the key"
      Version: "2012-10-17"
  Type: "AWS::KMS::Key"
DatalakeKMSAlias: 
  Properties: 
    AliasName: alias/Datalake-kms-key
    TargetKeyId: 
      Ref: DatalakeKey
  Type: "AWS::KMS::Alias"
 
