AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  DatalakeDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Name"
          AttributeType: "S"
        - 
          AttributeName: "Age"
          AttributeType: "N"
        - 
          AttributeName: "ID"
          AttributeType: "N"

      KeySchema: 
        - 
          AttributeName: "Name"
          KeyType: "HASH"
        - 
          AttributeName: "Age"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "DatalakeTableName"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "DatalakeGSI"
          KeySchema: 
            - 
              AttributeName: "ID"
              KeyType: "HASH"

          Projection: 
            NonKeyAttributes: 
              - "Name"
              - "Age"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

      LocalSecondaryIndexes: 
        - 
          IndexName: "DatalakeLSI"
          KeySchema: 
            - 
              AttributeName: "Name"
              KeyType: "HASH"
            - 
              AttributeName: "ID"
              KeyType: "RANGE"
          Projection: 
            NonKeyAttributes: 
              - "Age"
            ProjectionType: "INCLUDE"